### ISSUE TITLE
Need update README for build under Linux (Ubuntu Mate 20.04)

### ISSUE THREAD

**Issue by igavelyuk** [TheRainDoodle/Phenom-II-Benchmark#7]
Try to run from `linux_src_bin`

`$sudo ./phenom2_benchmark
sudo: ./phenom2_benchmark: command not found`
or 
`$sudo sh phenom2_benchmark 
phenom2_benchmark: 1: Syntax error: ")" unexpected`

`$uname -a
Linux igaveluyk-DS3 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Install as follow
`$sudo apt-get install build-essential`
`$pwd ~/Downloads/Phenom-II-Benchmark-master/linux_src_bin$ `
`$make`
`$make: 'phenom2_benchmark' is up to date.`
 - Remove `phenom2_benchmark` and `asm.o`
`sudo apt-get install nasm`
`$make
nasm asm.asm -felf64 -o asm.o
g++ main.cpp asm.o -lpthread -ffast-math -msse3 -O3 -o phenom2_benchmark`
- new `phenom2_benchmark` and `asm.o` files created
-----
- Does new file will be compiled the same way?, can upload new binary if needed (no idea how to check, but OLD binary not working)

**Comment by Rampagy** [comment]
When I tried it on my computer (Fedora 32) I had the same issue.  But then I remembered I never gave it execution permissions.  Can you give this a try and see if it fixes your issue?

    chmod +x phenom2_benchmark

**Comment by igavelyuk** [comment]
@Rampagy sorry for delay, It working after all steps I've done, I'm not a pro in compiling add for most people will be nice to have how-to. Program working like a charm, only one thing is interesting - before recompile give an error, after compile works great.

- If will have just little more time will PUSH update to your README.md 
- Will upload results from Rizen 1600af (stepping 2)
- Issue if you like you can close (but as reminder it works great)

**Comment by igavelyuk** [comment]
> chmod +x phenom2_benchmark

It is working for me and not need to rebuild
